### ISSUE TITLE
opensesame.exe and opensesamerun.exe ignore command-line arguments on Windows

### ISSUE THREAD

**Issue by EruIluvatar** [smathot/OpenSesame#437]
Under Win8.1, double-clicking on a .osxp file opens up the OpenSesame editor, but it displays the standard "New experiment" template instead of the selected experiment.
The experiment can only be opened through Files->Open...

**Comment by smathot** [comment]
Thanks for pointing this out. The problem comes from the `opensesame-windows-launcher`, which didn't preserve the command-line arguments that are needed to directly open or start experiments.

This should be fixed in v0.4.1 of `opensesame-windows-launcher`. Would you mind trying this out? To do so, open a windows command prompt in the OpenSesame program folder. Assuming that OpenSesame is installed in `c:\Program Files (x86)\OpenSesame` this works as follows:

1. Open the start menu, type `cmd.exe` and press enter to launch the command prompt.
2. Type `cd "c:\Program Files (x86)\OpenSesame"` to change to the OpenSesame program folder.
3. Type `Scripts\pip.exe install opensesame-windows-launcher --upgrade` to upgrade the launcher.

If you see no errors, you should now be able to open experiments directly by clicking on them, and to use opensesamerun as usual.

Please let me know if this works for you!

**Comment by EruIluvatar** [comment]
I can confirm, double-clicking an experiment opens OpenSesame correctly now. The startup seems to lag, it takes some seconds longer than e.g. Windows Excel even with a near-empty experiment.
But I think this is present in 3.1.0 as well.

Launching from CLI works also using `opensesame.exe [experiment]`.
However opensesamerun.exe is not fixed yet, still the same problem.

During the pip-upgrade, an error occured:
![pip-upgrade](https://cloud.githubusercontent.com/assets/5493667/16978252/51cf4508-4e5b-11e6-8436-2d5ad0f289be.png)

**Comment by smathot** [comment]
I tested it, and for me it actually worked fine. I think the upgrade just went wrong, although it's not clear to my why. I'll close this for now. If 3.1.2 is released and you still experience this problem, let me know and we'll re-open this issue.

> The startup seems to lag, it takes some seconds longer than e.g. Windows Excel even with a near-empty experiment. But I think this is present in 3.1.0 as well.

Yes, it's just a bit slow.

**Comment by EruIluvatar** [comment]
Hi Sebastiaan

I updated to 3.1.2 but the problem still remains.
What I tried unsuccessfully:
- normal on-top update with the windows installer
- uninstalling and fresh install of opensesame, however the installer still said that a previous version was installed in ...\Program Files (x86)\OpenSesame even though there was no folder left.
- do the pip upgrade with version 3.1.2, but the same error is thrown as in the screenshot (a backslash-escape problem in the pip-script?)

The portable version is running without problems so we will switch temporarily. The updating process is not as convenient though.

Thanks for your awesome work!

**Comment by EruIluvatar** [comment]
I just noticed that running opensesamerun.exe as admin works as expected but as user it doesn't. Despite the opensesame.exe and opensesamerun.exe binaries both had read, execute rights for users beforehand, and even after granting full rights to the user.

So I guess there's a library/executable down the runtime which needs admin rights anyway, I don't know an easy way to track it down on windows...

It would be much appreciated if we don't need admin rights for executing.
Students will run the study and they should not have admin rights...

**Comment by smathot** [comment]
Regarding the pip upgrade: This isn't necessary anymore, because the latest version of `opensesame-windows-launcher` is already bundled with 3.1.2. The crash is due to pip (part of Python) itself, which cannot deal with special characters. But it's not related to the issue per se.

> The portable version is running without problems so we will switch temporarily. The updating process is not as convenient though.

What do you mean? The whole open-experiment-on-doubleclick issue is only applicable to the installer, right? The portable version doesn't automatically register `.osexp` files. Or did you do this manually?

> I just noticed that running opensesamerun.exe as admin works as expected but as user it doesn't. Despite the opensesame.exe and opensesamerun.exe binaries both had read, execute rights for users beforehand, and even after granting full rights to the user.

I suspect that the issue is not rights, but special characters in the user profile. Could that be it? Does your username have non-ascii characters in it?

**Comment by EruIluvatar** [comment]
Sorry if it was confusing, I was talking about opensesamerun.exe only.
* `opensesame-windows-launcher`: Yes sure, the pip-upgrade was just a shot in the dark.
* open-experiment-on-doubleclick: This works perfectly with normal install, no problem here.
* special characters: Actually no, there are no special characters!

For example, this works (using portable version, no admin rights):
* `C:\Users\IMUCB_Lab\Downloads\opensesame_3.1.2-py2.7-win32-1\opensesamerun.exe C:\Users\IMUCB_lab\Desktop\Validierungsstudie\NeuesExperiment.osexp -s 1 -f`

But this does only work with admin rights (Installed OpenSesame 3.1.2):
* `"C:\Program Files(x86)\OpenSesame\opensesamerun.exe" C:\Users\IMUCB_lab\Desktop\Validierungsstudie\NeuesExperiment.osexp -s 1 -f`

Without admin rights, the opensesamerun-GUI opens up but still is not able to launch an experiment even when the `.osexp` is selected throught the file browser...

**Comment by EruIluvatar** [comment]
Stupid me, I found the problem.

It's because I didn't pass a path for the log file `opensesamerun.exe [experiment] -s 123 -l C:\path\to\log\folder`.

With the portable version, the logs are written by default to the `C:\...\Downloads\opensesame_3.1.2-py2.7-win32-1\`-folder to which of course the user has access.
With the installed version, it defaults to `C:\Program Files (x86)\OpenSesame` where admin rights are needed.

Sorry for the inconvenience, issue can be closed!

**Comment by smathot** [comment]
> Sorry for the inconvenience, issue can be closed!

Good!
